USE [master]
GO
/****** Object:  Database [Addons]    Script Date: 4/21/2020 9:42:59 PM ******/
CREATE DATABASE [Addons]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AlcoaAddons', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.INSIGHT\MSSQL\DATA\AlcoaAddons.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AlcoaAddons_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.INSIGHT\MSSQL\DATA\AlcoaAddons_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Addons] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Addons].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Addons] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Addons] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Addons] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Addons] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Addons] SET ARITHABORT OFF 
GO
ALTER DATABASE [Addons] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Addons] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Addons] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Addons] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Addons] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Addons] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Addons] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Addons] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Addons] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Addons] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Addons] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Addons] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Addons] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Addons] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Addons] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Addons] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Addons] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Addons] SET RECOVERY FULL 
GO
ALTER DATABASE [Addons] SET  MULTI_USER 
GO
ALTER DATABASE [Addons] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Addons] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Addons] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Addons] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Addons] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Addons] SET QUERY_STORE = OFF
GO
USE [Addons]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Addons]
GO
/****** Object:  Table [dbo].[__MigrationHistory]    Script Date: 4/21/2020 9:42:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__MigrationHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ContextKey] [nvarchar](300) NOT NULL,
	[Model] [varbinary](max) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC,
	[ContextKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Contacts]    Script Date: 4/21/2020 9:42:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contacts](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[Email] [nchar](10) NULL,
	[PhoneNumber] [nvarchar](50) NULL,
	[Status] [bit] NULL,
 CONSTRAINT [PK_dbo.Contacts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
 
GO
USE [master]
GO
ALTER DATABASE [Addons] SET  READ_WRITE 
GO
